# -*- coding: utf-8 -*-
"""Cópia de trabalho_looker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G3ngV0PwnYGdCoRy7jFhs-nq3KzL_51v

#Instalação de bibliotecas e importação#
"""

pip install gcsfs

pip install pandera

import pandas as pd
import os
import numpy as np
import pandera as pa
from google.cloud import storage

"""#Configuração pandas#"""

pd.set_option('display.max_columns',100)

"""#Conexão com o GCP#"""

serviceAccount = 'chave_google'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccount

client = storage.Client()
bucket = client.get_bucket('patriciamoraes1')
bucket.blob('PlanilhaVendas.xlsx')
path = 'gs://patriciamoraes1/brutos/PlanilhaVendas.xlsx'

"""#Extração#"""

df = pd.read_excel(path, parse_dates=['Unnamed: 4'])

"""#Análise Exploratória#"""

df.tail(5)

df.isna().sum()

df.tail(2)

df.DATA_HORA.head(2)

df.dtypes

df.head(2)

df.isna().sum()

ft_isna = df.ID.isna()
df.loc[ft_isna]

dfbackup = df.copy()

"""#Tratamento#"""

df.rename(columns ={
    'Unnamed: 0':'ID', 
          'Unnamed: 1':'PRODUTOS', 
          'Unnamed: 2':'QTD_PEDIDO',
          'Unnamed: 3':'PRECO_UNIT', 
          'Unnamed: 4':'DATA_HORA', 
          'Unnamed: 5':'DATA', 
          'Unnamed: 6':'ENDERECO_PED'
}, inplace=True)

df.DATA_HORA.replace(np.NaN,pd.NaT,inplace=True)

df.drop_duplicates(inplace=True, keep=False)

df.head(2)

df.drop(['DATA'],axis=1,inplace=True)

df.head(2)

df['DATA_HORA'] = pd.to_datetime(df['DATA_HORA'])

from datetime import datetime

df['QTD_PEDIDO'] = df['QTD_PEDIDO'].astype(int)
df['PRECO_UNIT'] = df['PRECO_UNIT'].astype(float)
df['ID'] = df['ID'].astype(int)

df.head(2)

df.dtypes

df['data'] = df.DATA_HORA.dt.date

df['mes_extenso'] = df['data'].dt.strftime('%B')

df['data'] = pd.to_datetime(df['data'])
df['data_extenso'] = df['data'].dt.strftime('%d/%B/%Y')

df['mes'] = df.data.dt.month

df.head(2)

df.head(2)

"""#Load#"""

df.to_csv('gs://patriciamoraes1/tratados/PlanilhaVendas.xlsx',index=False)